run:
  timeout: 5m
  go: '1.20'
  tests: false
  skip-dirs-use-default: true
  skip-dirs:
    - vendor
    - api/v1
    - internal/app/logistics/api/v1

output:
  sort-results: true

linters-settings:
  errcheck:
    check-blank: true
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true

linters:
  fast: true
